baseURL = 'https://example.org/'
languageCode = 'en-us'
title = '[TheRealGill]'
theme = "hugo-coder"
defaultContentLanguage = "en"
enableEmoji = true
relativeURLs = true

[pagination]
pagerSize = 15

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup]
[markup.highlight]
noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Matthew Gill"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Father | Husband | Problem Solver | Nerd"
keywords = "blog,problem solver,scripter,powershell,slice of life,system administrator,developer,personal"
info = [
  "Father | Husband | Problem Solver | Nerd"
]
avatarURL = "images/profile.webp"
#gravatar = "john.doe@example.com"
dateFormat = "January 2, 2006"
since = 2015
# Git Commit in Footer, uncomment the line below to enable it
#commit = "https://github.com/luizdepra/hugo-coder/tree/"
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/therealgill/"

[[params.social]]
name = "Facebook"
icon = "fa-brands fa-facebook fa-2x"
weight = 2
url = "https://www.facebook.com/therealgill"

[[params.social]]
name = "Bluesky"
icon = "fa-brands fa-bluesky fa-2x"
weight = 3
url = "https://bsky.app/profile/mg-trg.bsky.social"

[[params.social]]
name = "Twitter / X"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 4
url = "https://twitter.com/mg_therealgill/"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 5
url = "https://www.linkedin.com/in/matthewgill1/"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 6
url = "https://myhugosite.com/index.xml"
rel = "alternate"
type = "application/rss+xml"

[[menu.main]]
  name = "About Me"
  url = "/about/"
  weight = 30

[[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 30

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 30